version: "3.8"

services:

  db:
    image: postgres:12.18-bullseye
    container_name: db
    ports:
      - 1221:5432
    env_file:
      - .env-nondev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7
    container_name: redis
    command: --port 5370
    ports:
      - 5370



  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-nondev
    command: ["/app/docker/app.sh"]
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000

