"""tablefix

Revision ID: 5599ed1a620c
Revises: 0d7fac514852
Create Date: 2024-03-09 04:31:37.829287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5599ed1a620c'
down_revision: Union[str, None] = '0d7fac514852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registered_at')
    # ### end Alembic commands ###
