"""tasks no user

Revision ID: 0be226e9d36a
Revises: 45f0fe977abb
Create Date: 2024-04-20 03:36:58.164945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be226e9d36a'
down_revision: Union[str, None] = '45f0fe977abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_user_id_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_user_id_fkey', 'task', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
